#!/usr/bin/env python3

"""
Mikiri WAF CAPTCHA
Copyright (c) Mikiri Security, LLC
Author: Romanov R.
"""

import asyncio
import io
import json
import numpy as np
import random
import re
import secrets
import threading
import time

from concurrent.futures import ThreadPoolExecutor
from PIL import Image, ImageDraw, ImageFilter, ImageFont

from logger import log
from memcache import new_pool

##

memc_prefix = 'mikiri-waf-captcha_'
hdr_cpass_complete = {'x-waf-captcha-challenge': 'complete'}
hdr_cpass_progress = {'x-waf-captcha-challenge': 'progress'}

# session lifetime in the memcached, seconds
sid_ttl = 60

# the session id is generated by secrets.token_urlsafe()
sid_re = re.compile(r'^[A-Za-z0-9_-]{16,64}$')

# Slider puzzle. The sprite is the board with a gap, and the loose tile
# drawn at x=0 just under the board. templates/index.html crops that sprite
# and must use the same tile size.
BOARD_W = 480
BOARD_H = 220
PIECE = 72
PIECE_RADIUS = 16
# A finger is not pixel-perfect. The stored answer is the gap's x.
SLIDER_TOLERANCE = 8

##

# Replaced in gunicorn's post_fork so a worker never inherits the master's
# sockets. Tests replace this with an in-memory stand-in.
mclient = new_pool()

# The service runs under uvicorn. Memcached calls and image rendering must
# not run on the event loop, or one slow command stalls every request on
# the worker. Image rendering holds the GIL, so only a couple of those run
# at once; memcached calls release the GIL while they wait on the socket.
_io = None
_cpu = None
_pools_lock = threading.Lock()

# How many operations may be running or queued. Past this the request is
# dropped instead of piling up in an unbounded queue at several thousand RPS.
_IO_LIMIT = 32
_CPU_LIMIT = 4
_gates = {}
_busy_at = 0.0


class _Gate(object):
    def __init__(self, limit):
        self._limit = limit
        self._n = 0
        self._lock = threading.Lock()

    def enter(self):
        with self._lock:
            if self._n >= self._limit:
                return False
            self._n += 1
            return True

    def leave(self):
        with self._lock:
            self._n -= 1


def _executor(kind):
    global _io, _cpu
    with _pools_lock:
        if kind == 'io':
            if _io is None:
                _io = ThreadPoolExecutor(max_workers=8, thread_name_prefix='captcha-io')
            return _io
        if _cpu is None:
            _cpu = ThreadPoolExecutor(max_workers=2, thread_name_prefix='captcha-image')
        return _cpu


def _gate(kind):
    gate = _gates.get(kind)
    if gate is None:
        gate = _Gate(_IO_LIMIT if kind == 'io' else _CPU_LIMIT)
        _gates[kind] = gate
    return gate


def _busy(message):
    global _busy_at
    now = time.monotonic()
    if now - _busy_at < 1:
        return
    _busy_at = now
    log.error(message)


async def _run(kind, fn, *args, limit=True):
    gate = _gate(kind) if limit else None
    if gate is not None and not gate.enter():
        _busy('CAPTCHA worker is overloaded, request dropped')
        return None
    try:
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(_executor(kind), fn, *args)
    finally:
        if gate is not None:
            gate.leave()


def reopen_memcache():
    """New pool after fork. Sockets from the master must not be shared."""
    global mclient, _io, _cpu, _busy_at
    mclient = new_pool()
    old = (_io, _cpu)
    _io = None
    _cpu = None
    _gates.clear()
    _busy_at = 0.0
    for executor in old:
        if executor is not None:
            executor.shutdown(wait=False)


def _err(exc):
    text = str(exc).strip()
    if text:
        return text
    return type(exc).__name__


def valid_sid(sid):
    """The session id comes from the client and is used as a memcached key."""

    return bool(sid) and bool(sid_re.match(sid))


def answers_match(given, expected):
    """True when the slider is within a few pixels of the gap."""

    try:
        return abs(int(str(given).strip()) - int(str(expected).strip())) <= SLIDER_TOLERANCE
    except (TypeError, ValueError):
        return False


def captcha_challenge():
    """Horizontal position of the gap. Never the slider's starting point."""

    low = PIECE + 24
    high = BOARD_W - PIECE - 16
    return str(low + secrets.randbelow(high - low + 1))


def _puzzle_background(width, height):
    """Soft color field. The glow is not periodic, so the tile fits one gap."""

    ys = np.linspace(0.0, 1.0, height, dtype=np.float32)[:, None]
    xs = np.linspace(0.0, 1.0, width, dtype=np.float32)[None, :]
    rgb = np.dstack((
        14 + 10 * ys + 18 * xs,
        22 + 16 * ys + 28 * xs,
        48 + 24 * ys + 55 * xs,
    )).clip(0, 255).astype(np.uint8)
    image = Image.fromarray(rgb, 'RGB').convert('RGBA')

    glow = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(glow)
    colors = (
        (37, 99, 235, 200),
        (56, 189, 248, 170),
        (99, 102, 241, 160),
        (125, 211, 252, 150),
        (167, 139, 250, 140),
        (14, 165, 233, 180),
    )
    mid = height // 2
    for i, color in enumerate(colors):
        cx = int((i + 0.25 + random.random() * 0.5) * width / len(colors))
        cy = mid + random.randint(-36, 36)
        rad = random.randint(52, 84)
        draw.ellipse((cx - rad, cy - rad, cx + rad, cy + rad), fill=color)
    glow = glow.filter(ImageFilter.GaussianBlur(radius=16))
    image = Image.alpha_composite(image, glow)
    return _paint_mark(image)


def _paint_mark(image):
    """
    Barely-visible wordmark across almost the whole field.

    Mikiri is sized to most of the width and WAF sits under it. Both are
    blurred into the color, so a tile cropped from the middle picks up soft
    light rather than a sharp piece of a letter.
    """

    layer = Image.new('RGBA', image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    name = 'Mikiri'
    mark = 'WAF'

    probe = ImageFont.load_default(100)
    probe_box = draw.textbbox((0, 0), name, font=probe)
    name_size = max(8, round(100 * (image.width * 0.90) / (probe_box[2] - probe_box[0])))
    mark_size = max(8, round(name_size * 0.62))
    name_font = ImageFont.load_default(name_size)
    mark_font = ImageFont.load_default(mark_size)

    name_box = draw.textbbox((0, 0), name, font=name_font)
    mark_box = draw.textbbox((0, 0), mark, font=mark_font)
    name_w = name_box[2] - name_box[0]
    name_h = name_box[3] - name_box[1]
    mark_w = mark_box[2] - mark_box[0]
    mark_h = mark_box[3] - mark_box[1]
    gap = max(2, round(name_size * 0.025))
    top = (image.height - name_h - gap - mark_h) // 2

    draw.text(
        ((image.width - name_w) // 2 - name_box[0], top - name_box[1]),
        name,
        font=name_font,
        fill=(236, 244, 255, 110),
    )
    draw.text(
        ((image.width - mark_w) // 2 - mark_box[0], top + name_h + gap - mark_box[1]),
        mark,
        font=mark_font,
        fill=(186, 214, 255, 120),
    )
    layer = layer.filter(ImageFilter.GaussianBlur(radius=max(6, round(name_size * 0.055))))
    return Image.alpha_composite(image, layer)


def _rounded_mask(size, radius):
    mask = Image.new('L', (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, size - 1, size - 1),
        radius=radius,
        fill=255,
    )
    return mask


def render_puzzle(target_x):
    """
    PNG sprite: the board, then the loose tile at the left of the next row.
    target_x is the gap position in board pixels.
    """

    piece_y = (BOARD_H - PIECE) // 2
    board = _puzzle_background(BOARD_W, BOARD_H)
    gap = (target_x, piece_y, target_x + PIECE - 1, piece_y + PIECE - 1)
    tile = board.crop((target_x, piece_y, target_x + PIECE, piece_y + PIECE))
    tile.putalpha(_rounded_mask(PIECE, PIECE_RADIUS))

    # The gap keeps a dim copy of the picture, so it reads as a slot
    # rather than a black sticker. The loose tile is the bright piece.
    veil = Image.new('RGBA', board.size, (0, 0, 0, 0))
    veil_draw = ImageDraw.Draw(veil)
    veil_draw.rounded_rectangle(gap, radius=PIECE_RADIUS, fill=(4, 8, 20, 165))
    board = Image.alpha_composite(board, veil)
    rim = Image.new('RGBA', board.size, (0, 0, 0, 0))
    ImageDraw.Draw(rim).rounded_rectangle(
        gap,
        radius=PIECE_RADIUS,
        outline=(255, 255, 255, 40),
        width=1,
    )
    board = Image.alpha_composite(board, rim)

    sprite = Image.new('RGBA', (BOARD_W, BOARD_H + PIECE), (0, 0, 0, 0))
    sprite.paste(board, (0, 0))
    sprite.paste(tile, (0, BOARD_H), tile)

    out = io.BytesIO()
    sprite.save(out, format='PNG')
    out.seek(0)
    return out


def _captcha_img_gen(sid):
    try:

        # the session id is a part of the memcached key
        if not valid_sid(sid):
            return None

        # receive data from the memcached
        memout = mclient.get(memc_prefix + sid)
        if not memout:
            return None

        try:
            target_x = int(json.loads(memout).get('answer'))
        except (TypeError, ValueError):
            return None
        if target_x < 0 or target_x > BOARD_W - PIECE:
            return None

        return render_puzzle(target_x)

    except Exception as e:
        log.error('An error occurred during CAPTCHA generation for SID {}: {}'.format(sid, _err(e)))
        return None


async def captcha_img_gen(sid):
    return await _run('cpu', _captcha_img_gen, sid)


def _session_get(sid):
    """Returns the stored answer for the session, None when there is none."""
    try:

        if not valid_sid(sid):
            return None

        memout = mclient.get(memc_prefix + sid)
        if not memout:
            return None

        return json.loads(memout).get('answer')

    except Exception as e:
        log.error('An error occurred while reading the session {}: {}'.format(sid, _err(e)))
        return None


async def session_get(sid):
    return await _run('io', _session_get, sid)


def _session_drop(sid):
    """Removes a solved session so that it cannot be replayed."""
    try:

        if valid_sid(sid):
            mclient.delete(memc_prefix + sid)

    except Exception as e:
        log.error('An error occurred while removing the session {}: {}'.format(sid, _err(e)))


async def session_drop(sid):
    # A solved session has to be removed even when the worker is at the cap.
    return await _run('io', _session_drop, sid, limit=False)


def _request_preprocessing():
    """Creates a new CAPTCHA session and returns its id."""
    try:

        # init: an unpredictable, non-reusable session id
        sid = secrets.token_urlsafe(16)

        # the gap position is the only secret; the picture is drawn from it
        answer = captcha_challenge()

        # update the sessions
        mclient.set(
            memc_prefix + sid,
            json.dumps({
                'answer': answer,
            }), sid_ttl
        )

        # return
        return sid

    except Exception as e:
        log.error('An error occurred while creating the CAPTCHA session: {}'.format(_err(e)))
        return None


async def request_preprocessing():
    return await _run('io', _request_preprocessing)
